### ISSUE TITLE
Swagger UI?

### ISSUE THREAD

**Issue by roncewind** [Senzing/aws-cloudformation-dev-rest#38]
Should we include swagger UI in the dev-rest stack?

**Comment by mahchiahui** [comment]
@roncewind https://github.com/Senzing/aws-cloudformation-dev-rest/blob/main/docs/postman.md

**Comment by mahchiahui** [comment]
this is where the link is in the documentation
https://github.com/Senzing/aws-cloudformation-dev-rest#using-postman

**Comment by roncewind** [comment]
PR merged
